In [6]:
import numpy as np

**Creando una lista de 10 elementos**

In [7]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**Transformando la lista a un array**

In [8]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Corroborando el tipo de estructura**

In [9]:
type(arreglo)

numpy.ndarray

**Corroborando el tipo de datos del arreglo**

In [10]:
arreglo.dtype

dtype('int32')

**Definiendo el array de int32 a float32**


In [11]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

**Sigue siendo un array de int32**

In [12]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Transformando los datos de int32 a float32**

In [13]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

**También existe una función similar a range pero ocupan arrays**

In [ ]:
arreglonuevo = np.arange(1,11)
arreglonuevo

**Arreglo de 2 en 2 utilizando Arange**

**Obteniendo el promedio en array**

In [ ]:
promedio = np.mean(arreglo)
promedio

**Obteniendo la mediana**

In [ ]:
mediana = np.median(arreglo)

**Desviacion estandar del arreglo**

In [ ]:
desviacion_std = np.std(arreglo)

**Generación de un arreglo de solo unos**

In [ ]:
arreglo_de_unos = np.ones(1o)
arreglo_de_unos

**Transformando el arreglo de unos puntos flotantes a enteros**

In [ ]:
arreglo:int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

**Generación de un arreglo de 5 elementos de solo 0**

In [ ]:
**Utiliz**